### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by wkhere** [gijit/gi#26]
Hi!
Having `gi` working with recent changes in Go, I'm now struggling with this:

```
import "io/ioutil"
oops: 'problem detected during Go static type checking: 'where error? err = '1:8: could not import io/ioutil (erro: package 'io/ioutil' unknown, or not shadowed. To shadow it, run gen-gijit-shadow-import on the package, add a case and import above, and recompile gijit.)''' on input 'import "io/ioutil"'
```
The same with many other packages, including my own packages.

So what is the workflow?
What does it mean "add a case and import above"?
Do I need to recompile `gi` every time I'd need to use a new package?

TIA

**Comment by glycerine** [comment]
I've added a highlight link to the README to where this is discussed. https://github.com/gijit/gi#binary-imports gives the overview.

Yes, packages you want to import must be shadowed (sandboxed) first. This involves
compiling them into the binary. This allows reflect to work, and reflect is
how we instantiate values from imported packages. Otherwise embedded
methods are lost, due to gaps in the Go reflect system that the Go team
declines to fix since it involves runtime code generation. Eventually once
everything is working, we should be able to import packages and jit compile
them with LuaJIT, but we aren't there yet.  Related issue on the current
limitations is https://github.com/gijit/gi/issues/21 ; method calls into
foreign packages currently work, but dealing with their types may not yet.

See pkg/compiler/import.go for examples of the additions needed to import.go, and commit 8a5c8c9 gives an example for io/ioutil; where

pkg/compiler/shadow/io/ioutil/ioutil.genimp.go is the output of running 
~~~
gen-gijit-shadow-import io/ioutil
~~~

**Comment by wkhere** [comment]
Thx for the answer.

Explanation is valid, although the whole thing is not exactly what I was looking for.

Good luck with your project!
