### ISSUE TITLE
usability at 1.0

### ISSUE THREAD

**Issue by glycerine** [gijit/gi#28]
@elliott5 @sbinet @crawshaw

I've released 1.0 which can compile quite a bit. Chan/select/goroutines are still not implemented, but I brought over the full type system from GopherJS.

If you are so inclined, I would be glad to have some usability feedback. Please give it a try and let me know all the little things that seem unintuitive. 

No issue is too small to mention.

Thank you.

Jason

**Comment by elliott5** [comment]
Hi Jason,

Simple REPL go works well for trivial testing.

So I tried to test `github.com/elliott5/go-sequitur`...

It took me a long time to get `gen-gijit-shadow-import` working (I didn't realize I needed the `.a` file), and the whole process of updating the import `Go` file is **very**  clanky! Also because the package name is different from the import path I had to change some names (from `import.go`):
```
	case "github.com/elliott5/go-sequitur":
		luar.Register(ic.vm, "sequitur", shadow_sequitur.Pkg)
```

Then I came across the problem that `[]byte("someString") ` does not work!

Finally got some code that executes ... and fails.
```
gi> import "github.com/elliott5/go-sequitur"

elapsed: '20.992µs'
gi>  x := sequitur.Parse([]byte{'a','a','a','b','b','b','a','a','a','x'})

elapsed: '136.205µs'
gi> x
nil

elapsed: '93.004µs'
```

...and I had to call a halt, before I spent the entire day on it :)

**Comment by glycerine** [comment]
@elliott5 Awesome! Great feedback!

I agree with the shadow imports being clunky. I ported part of the GopherJS build system, with the aim of eventually being able to build all packages in Lua land rather than have mixed Go/Lua (so that shadow imports won't be necessary)... but the build system is large and complex and so the port is not yet finished.

>  []byte("someString") does not work

Great catch! I'll get on to fixing that.

**Comment by glycerine** [comment]
> []byte("someString") does not work
>> Great catch! I'll get on to fixing that.

[]byte to string and string to []byte conversions are working in the latest release, v1.0.11.

**Comment by glycerine** [comment]
imports are captured in their own issue, https://github.com/gijit/gi/issues/27, and the string <-> []byte is fixed. Closing this out just to clean up.
