### ISSUE TITLE
error setting the last element of multi-dimensional array

### ISSUE THREAD

**Issue by cosmos72** [gijit/gi#47]
I noticed this error while trying to use arrays instead of slices in the matrix multiplication example
[pkg/compiler/_bench/matmul.gijit](../blob/master/pkg/compiler/_bench/matmul.gijit)

```
gi> var a [5][5]float64
elapsed: '224.969µs'
gi> a[4][3]
0
elapsed: '78.885µs'
gi> a[4][4]
0
elapsed: '64.524µs'
gi> a[4][3]=1.0
elapsed: '64.095µs'
gi> a[4][4]=1.0
error! __errHandlerForEval sees err =	[string "-- prelude defines things that should..."]:24: index out of range
[string "-- prelude defines things that should..."]:24: index out of range
stack traceback:
	[string "--..."]:3242: in function <[string "--..."]:3239>
	[C]: in function 'error'
	[string "-- prelude defines things that should..."]:24: in function '__gi_SetRangeCheck'
	[string "..."]:1: in function 'chunk'
	[string "--..."]:3270: in function <[string "--..."]:3270>
	[C]: in function 'xpcall'
	[string "--..."]:3270: in function '__gijitMainEval'
	[string "--..."]:3302: in function <[string "--..."]:3302>
```
Note: slices and one-dimensional arrays do not show this problem

**Comment by glycerine** [comment]
@cosmos72 very cool. good catch. If you need a quick workaround, you can disable the runtime type checks by commenting out the check in the function

 https://github.com/gijit/gi/blob/master/pkg/compiler/prelude/prelude.lua#L21

so that 
~~~
function __gi_SetRangeCheck(x, i, val)
  --print("SetRangeCheck. x=", __st(x), " i=", i, " val=", val)
  if x == nil or i < 0 or i >= #x then
     error("index out of range")
  end
  x[i] = val
  return val
end;

~~~
becomes
~~~
function __gi_SetRangeCheck(x, i, val)
  --print("SetRangeCheck. x=", __st(x), " i=", i, " val=", val)
  --if x == nil or i < 0 or i >= #x then
  --   error("index out of range")
  --end
  x[i] = val
  return val
end;
~~~
Of course that's somewhat dangerous. Even though the compile time bounds checking generally catches many if not most issues, it can't catch indexes that are computed at runtime.

NB to future self: It appears the deeper issue is that the inner/leaf array from the 2nd dimension is missing all of its metatable type information. Hence the `#` or length method isn't overridden, and so Lua's default applies, which misses the 0-th element since Lua arrays start at 1.

**Comment by cosmos72** [comment]
It's interesting that *reading* the last element (`a[4][4]` in the example) works, but setting it (`a[4][4] = 1.0`) fails.  
Maybe it can help?

**Comment by glycerine** [comment]
I think I got it. Give the latest a try. Let me know if you find anything else.

**Comment by cosmos72** [comment]
Confirmed, now it works. Thanks!
